name: Build and Deploy ASP.NET Core Web App

on:
  push:
    branches:
      - master 
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Używamy standardowego i szybszego Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build and publish Web project
        run: dotnet publish ./HelpDeskTicketing.Web/HelpDeskTicketing.Web.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'helpdesk-web-frontend' # Upewnij się, że to DOKŁADNA nazwa
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_... }} # Zostaw bez zmian
          package: ./publish # <-- KLUCZOWA ZMIANA: Jawnie wskazujemy folder z opublikowanymi plikami
